###Querying and Setting Telegram Webhooks

@bot_key = bot437966140:AAFqH9MedcP32nae4TdvF77L_3oM5Q5fVm0

###  Querying webhook:
GET https://api.telegram.org/{{bot_key}}/getWebhookInfo


### Setting up webhook
GET https://api.telegram.org/{{bot_key}}/setWebhook?url=<webhook_url>
